source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!

target 'Lasso_Example' do

  # Set up SwiftLint
  pod 'SwiftLint'
  script_phase :name => 'SwiftLint',
               :script => "${PODS_ROOT}/SwiftLint/swiftlint" \
                          " --config ${SRCROOT}/../.swiftlint.yml" \
                          " --path ${SRCROOT}"

  # WWLayout for easy constraints
  pod 'WWLayout'

  # Lasso
  pod 'Lasso', :path => '../'

end

target 'Lasso_Tests' do
  pod 'WWLayout'
  pod 'Lasso', :path => '../'
end

target 'Lasso_TestUtilities_Tests' do
  pod 'LassoTestUtilities', :path => '../'
end

target 'Lasso_Example_Tests' do
  pod 'LassoTestUtilities', :path => '../'
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "WW International"
  installer.pods_project.root_object.attributes["LastUpgradeCheck"] = '1300'
  
  # Install Lasso templates 
  installer.pod_targets.each do |pod|
    if pod.name == "Lasso"
      path = File.expand_path("#{Dir.pwd}/Pods#{pod.pod_target_srcroot}")
      system("make -C #{path}/Templates install")
    end
  end
  
  # Minimum Simulator deployment target is 9.0
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      version = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      unless version.nil? || Gem::Version.new(version) >= Gem::Version.new('9.0')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end

  # Support for CircleCI to run unit tests against multiple swift versions.
  # Don't include this logic (or a `.swift-version` file) in your projects.
  if File.file?('.swift-version')
    swift_version = File.read('.swift-version')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = "#{swift_version.strip}"
      end
    end
  end
end
