# iOS CircleCI configuration file
#
version: 2.1

defaults: &defaults
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -o pipefail

commands:

  # Sets Ruby version and installs all gems, using a cache
  setup_ruby:
    parameters:
      version:
        type: string
        default: '2.6'
    steps:
      - run:
          name: Install ffi
          command: |
            brew reinstall libffi
            export LDFLAGS="-L/usr/local/opt/libffi/lib"
            export CPPFLAGS="-I/usr/local/opt/libffi/include"
      - run:
          name: Set Ruby version
          command: echo 'chruby ruby-<< parameters.version >>' >> ~/.bash_profile
      - restore_cache:
          keys:
            - gem-cache-v<< parameters.version >>-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v<< parameters.version >>-{{ arch }}-{{ .Branch }}
      - run:
          name: Install bundler
          command: sudo gem update bundler -f
      - run:
          name: Configure bundler
          command: |
            bundle config set path ~/vendor/bundle
            bundle config --global build.ffi --disable-system-libffi
      - run:
          name: Install dependencies in Gemfile
          command: bundle install
      - save_cache:
          key: gem-cache-v<< parameters.version >>-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/vendor/bundle
  
  # Installs utilities from Homebrew, and gems from the Gemfile
  install_dependencies:
    parameters:
      ruby:
        type: string
        default: '2.6'
    steps:
      - setup_ruby:
          version: << parameters.ruby >>

  # Runs `pod update`
  pod_update:
    parameters:
      swift:
        type: string
        default: '5.0'
    steps:
      - run:
          name: Set Swift language version
          command: echo "<< parameters.swift >>" > Example/.swift-version
      - run:
          name: Pod Update
          command: |
            cd Example && bundle exec pod update

  # Build the Example app & run the tests
  build:
    steps:
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan --workspace "Example/Lasso.xcworkspace"
          #command: fastlane scan --workspace "Example/Lasso.xcworkspace" --code_coverage --output_directory output/scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Lasso-Example
  
  # Build the SwiftPM Example app & run the tests
  build_swiftpm:
    steps:
      - run:
          name: Build and run tests
          command: >-
            xcodebuild build
            -project "Example/SwiftPM/Lasso-SwiftPM/Lasso-SwiftPM.xcodeproj"
            -scheme "Lasso-SwiftPM"
            -destination "platform=iOS Simulator,name=iPhone 11"

jobs:

  build-gem-cache-26:
    <<: *defaults
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - setup_ruby:
          version: '2.6'

  build-gem-cache-27:
    <<: *defaults
    macos:
      xcode: 12.0.0
    steps:
      - checkout
      - setup_ruby:
          version: '2.7'

  build-and-test-swift42:
    <<: *defaults
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.6'
      - pod_update:
          swift: '4.2'
      - build

  build-and-test-swift5:
    <<: *defaults
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.6'
      - pod_update:
          swift: '5.0'
      - build

  build-and-test-swift51:
    <<: *defaults
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.6'
      - pod_update:
          swift: '5.1'
      - build

  build-and-test-swift52:
    <<: *defaults
    macos:
      xcode: 11.4.0
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.6'
      - pod_update:
          swift: '5.2'
      - build

  build-and-test-swift53:
    <<: *defaults
    macos:
      xcode: 12.0.0
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.7'
      - pod_update:
          swift: '5.3'
      - build

  build-and-test-swiftpm:
    <<: *defaults
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - install_dependencies:
          ruby: '2.6'
      - build_swiftpm

workflows:
  version: 2

  build-test:
    jobs:
      - build-gem-cache-26
      - build-gem-cache-27
      - build-and-test-swift42:
          requires:
            - build-gem-cache-26
      - build-and-test-swift5:
          requires:
            - build-gem-cache-26
      - build-and-test-swift51:
          requires:
            - build-gem-cache-26
      - build-and-test-swift52:
          requires:
            - build-gem-cache-26
      - build-and-test-swift53:
          requires:
            - build-gem-cache-27
      - build-and-test-swiftpm:
          requires:
            - build-gem-cache-26
