name: Build and test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-macOS-12:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        xcode-version: [13.4.1, 14.0.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies in Gemfile
        run: bundle install
       
      - name: Install dependencies in Podfile
        working-directory: Example
        run: bundle exec pod update

      - name: Build and run tests
        working-directory: Example
        run: bundle exec fastlane scan
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer

      - name: Post job cleanup
        run: git clean -ffdxq
        if: always()
        continue-on-error: true
  
  build-and-test-macOS-13:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        xcode-version: [14.2, 14.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies in Gemfile
        run: bundle install
       
      - name: Install dependencies in Podfile
        working-directory: Example
        run: bundle exec pod update

      - name: Build and run tests
        working-directory: Example
        run: bundle exec fastlane scan
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer

      - name: Post job cleanup
        run: git clean -ffdxq
        if: always()
        continue-on-error: true

  build-and-test-swiftpm:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies in Gemfile
        run: bundle install

      - name: Build and run tests
        run: |
          xcodebuild build \
            -project "Example/SwiftPM/Lasso-SwiftPM/Lasso-SwiftPM.xcodeproj" \
            -scheme "Lasso-SwiftPM" \
            -destination "platform=iOS Simulator,name=iPhone 11"

      - name: Post job cleanup
        run: git clean -ffdxq
        if: always()
        continue-on-error: true

  build-and-test-tuist:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Clean
        working-directory: Example
        run: tuist clean

      - name: Fetch dependencies
        working-directory: Example
        run: tuist fetch
      
      - name: Generate project
        working-directory: Example
        run: tuist generate --no-open
      
      - name: Build and run tests
        working-directory: Example
        run: tuist test

      - name: Post job cleanup
        run: git clean -ffdxq
        if: always()
        continue-on-error: true
